### ISSUE TITLE
可以用了吗？

### ISSUE THREAD

**Issue by ilongjiang** [shaonianzhentan/google_maps#1]
可以使用了吗

**Comment by shaonianzhentan** [comment]
可以用吧

**Comment by Tao173** [comment]
> 可以用吧

请问这个和你之前那个百度地图除了能集成添加还有什么区别嘛？？是准备全部迁移到这个嘛？？我今天安装这个了，原来的那个卸载了。。。感谢开发！

**Comment by shaonianzhentan** [comment]
1. 右键点击实体图标会自动居中
2. 支持显示地铁线路图
3. 支持设置我的家的位置

之前那个搞的太复杂了，一些功能没啥用，所以不会更新了，本插件以简单为主

**Comment by ilongjiang** [comment]
大神我安装以后怎么打不开呢？？
