### ISSUE TITLE
添加集成以后打开地图一片空白

### ISSUE THREAD

**Issue by catchfishday** [shaonianzhentan/google_maps#11]
大佬，请教一下，百度地图开放平台申请了浏览器端ak，白名单没做限制，百度后台也统计了使用次数，homeassistant前端地图始终一片空白，不知道咋回事

![image](https://github.com/shaonianzhentan/google_maps/assets/12185015/a84d271a-bf1d-44f8-9b84-ae20fcfdec0d)
![image](https://github.com/shaonianzhentan/google_maps/assets/12185015/f6ae3a66-8d84-4828-afaa-2e0367e7eb68)

**Comment by shaonianzhentan** [comment]
按F12开启调试工具，在控制台中查看错误信息

**Comment by catchfishday** [comment]
> 今天换了一个网络环境居然可以正常展示了，谢谢
