### ISSUE TITLE
是不是失效了

### ISSUE THREAD

**Issue by verysun** [shaonianzhentan/google_maps#2]
![image](https://user-images.githubusercontent.com/30220649/170396399-92da057a-735b-450f-928b-86654e416a66.png)
安装打开后显示空白

**Comment by Zynismus16** [comment]
我也是
f12看控制台发现少了个js文件
[RichMarker.min.js](https://mapopen.bj.bcebos.com/github/BMapGLLib/RichMarker/src/RichMarker.min.js)

直接访问提示不安全，也不能手动下载替换，只能去网上找找看了

**Comment by shaonianzhentan** [comment]
> 我也是 f12看控制台发现少了个js文件 [RichMarker.min.js](https://mapopen.bj.bcebos.com/github/BMapGLLib/RichMarker/src/RichMarker.min.js)
> 
> 直接访问提示不安全，也不能手动下载替换，只能去网上找找看了

大部分都是因为网络问题，导致无法加载核心的地图依赖文件，从而无法显示
![image](https://user-images.githubusercontent.com/5294022/201503891-eeb37e2e-991e-43c5-9719-d3019e9f6f1f.png)

**Comment by Zynismus16** [comment]
> > 我也是 f12看控制台发现少了个js文件 [RichMarker.min.js](https://mapopen.bj.bcebos.com/github/BMapGLLib/RichMarker/src/RichMarker.min.js)
> > 直接访问提示不安全，也不能手动下载替换，只能去网上找找看了
> 
> 大部分都是因为网络问题，导致无法加载核心的地图依赖文件，从而无法显示 ![image](https://user-images.githubusercontent.com/5294022/201503891-eeb37e2e-991e-43c5-9719-d3019e9f6f1f.png)

刚试了一下， 该文件又能访问了，尝试本地化成功，另外我看了下地图，在有三维建筑的情况下默认视图是顶视图，请问我该怎么去改倾斜度
