### ISSUE TITLE
谢谢开发者的付出。请问一下这个插件怎么重装？

### ISSUE THREAD

**Issue by fusang1337** [shaonianzhentan/google_maps#3]
我删除了hassio\custom_components\google_maps目录 重启之后就安装不上了，显示  此集成不支持通过 UI 配置。如果您是从 Home Assistant 网站点击链接前来，请确保您运行的是最新版本的 Home Assistant。

**Comment by shaonianzhentan** [comment]
关注公众号，多看看基础教程
https://mp.weixin.qq.com/s/FTzDC1lPUCfdw7w9xrA8sA

**Comment by fusang1337** [comment]
谢谢 已重装
