### ISSUE TITLE
能支持火星系坐标吗？

### ISSUE THREAD

**Issue by syzylj** [shaonianzhentan/google_maps#5]
很喜欢你这个插件，TRACCAR用的高德地图版后，位置在插件里有偏移，希望能支持高德国内坐标。谢谢！

**Comment by syzylj** [comment]
看到你的代码里有高德相关的转换代码，但没有相应的配置说明，能提供吗？感谢！

**Comment by shaonianzhentan** [comment]
自定义实体，定义map属性为gaode就好了

```yaml
person.xxxxx:
  map: gaode
```

**Comment by syzylj** [comment]
已在customize.yam自定义实体，加入map值为gaode，系统内设备已经显示有MAP属性，但位置没有变化，是不是我理解错误了，请指教。

**Comment by syzylj** [comment]
清理了缓存，位置显示没有问题了，但轨迹仍然是原来的，有偏差

**Comment by shaonianzhentan** [comment]
> 清理了缓存，位置显示没有问题了，但轨迹仍然是原来的，有偏差

轨迹忘记改了😂

**Comment by syzylj** [comment]
感谢，现在已经使用正常了
