### ISSUE TITLE
Homeassistant更新5月版本后打不开了

### ISSUE THREAD

**Issue by skypjsfly** [shaonianzhentan/google_maps#8]
报错如图，打开地图就什么都不显示，求解答是什么问题，在5月之前的版本都是正常的
Logger: frontend.js.latest.202305033
Source: components/system_log/__init__.py:257
First occurred: 2023年5月6日 17:45:17 (20 occurrences)
Last logged: 12:01:25

https://*********local/amap/amap-panel.js:8:5 Uncaught ReferenceError: Polymer is not defined
https://**********/local/amap/amap-panel.js:8:5 Uncaught ReferenceError: Polymer is not defined

![Screenshot_2023-05-11-12-04-28-500_io homeassistant companion android-edit](https://github.com/shaonianzhentan/google_maps/assets/32484309/e1a3b7e7-1a74-4316-9e26-39a0d100be68)

**Comment by shaonianzhentan** [comment]
高德地图卡片，咋提到百度地图这里了？？？

**Comment by skypjsfly** [comment]
> 高德地图卡片，咋提到百度地图这里了？？？
抱歉，找错项目了
